# Default values for frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

production:
  deployment: green

green:
  image:
    repository: risla8/poc
    pullPolicy: IfNotPresent
    tag: latest
  replicaCount: 3

blue:
  image:
    repository: risla8/poc
    pullPolicy: IfNotPresent
    tag: new
  replicaCount: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  path: /
  hosts:
    prod: poc.172.28.128.4.xip.io
    staging: staging.poc.172.28.128.4.xip.io
