kind: pipeline
name: staging

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: risla8/poc
      tags:  ${DRONE_COMMIT_SHA:0:8}
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    branch:
      - master
    event:
      - push

  - name: deploy
    image: risla8/drone
    commands:
      - /kube.sh
      - helm upgrade --install frontend --namespace default ./frontend --reuse-values --set $(./scripts/switchdeploy.sh).image.tag=${DRONE_COMMIT_SHA:0:8}
    environment:
      KUBERNETES_NAMESPACE:
        from_secret: k8s_ns
      KUBERNETES_TOKEN:
        from_secret: k8s_token
      KUBERNETES_CA:
        from_secret: k8s_ca
      KUBERNETES_APISERVER:
        from_secret: k8s_apiserver
    when:
      branch:
        - master
      event:
        - push
---
kind: pipeline
name: switch

steps:
  - name: blue-green-switch
    image: risla8/drone
    commands:
      - /kube.sh
      - ./scripts/switchdeploy.sh deploy
    environment:
      KUBERNETES_NAMESPACE:
        from_secret: k8s_ns
      KUBERNETES_TOKEN:
        from_secret: k8s_token
      KUBERNETES_CA:
        from_secret: k8s_ca
      KUBERNETES_APISERVER:
        from_secret: k8s_apiserver
      HELM_CHART_DIR: "./frontend"
    when:
      event:
        - promote
      target:
        - switch
---
kind: pipeline
name: staging-rollback

steps:
  - name: rollback
    image: risla8/drone
    commands:
      - /kube.sh
      - helm upgrade --install frontend ./frontend --reuse-values --set $(./scripts/switchdeploy.sh).image.tag=${DRONE_COMMIT_SHA:0:8}
    environment:
      KUBERNETES_NAMESPACE:
        from_secret: k8s_ns
      KUBERNETES_TOKEN:
        from_secret: k8s_token
      KUBERNETES_CA:
        from_secret: k8s_ca
      KUBERNETES_APISERVER:
        from_secret: k8s_apiserver
    when:
      event:
        - promote
      target:
        - rollback
