apiVersion: v1
kind: ConfigMap
metadata: 
  name: {{ include "frontend.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "frontend.name" . }}
    helm.sh/chart: {{ include "frontend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  nginx.conf: |
    server {
    listen 80;
    server_name _;

    root /var/www/;
    index index.html;

    location / {
        try_files $uri /index.html;
        }
    }
