{{- if .Values.ingress.enabled -}}
{{- $fullName := include "frontend.fullname" . -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "frontend.name" . }}
    helm.sh/chart: {{ include "frontend.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{ .Values.ingress.hosts.prod }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-prod
              servicePort: 80
    - host: {{ .Values.ingress.hosts.staging }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $fullName }}-staging
              servicePort: 80
{{- end }}
